DIRECTION_LOOKUPS = {
    'WEST': 'W',
    'W': 'W',
    'SW': 'SW',
    'SOUTH-WEST': 'SW',
    'SOUTHWEST': 'SW',
    'SOUTH-EAST': 'SE',
    'SOUTHEAST': 'SE',
    'SOUTH_WEST': 'SW',
    'SOUTH_EAST': 'SE',
    'SOUTH': 'S',
    'SOUTH WEST': 'SW',
    'SOUTH EAST': 'SE',
    'SE': 'SE',
    'S': 'S',
    'NW': 'NW',
    'NORTH-WEST': 'NW',
    'NORTHWEST': 'NW',
    'NORTH-EAST': 'NE',
    'NORTHEAST': 'NE',
    'NORTH_WEST': 'NW',
    'NORTH_EAST': 'NE',
    'NORTH': 'N',
    'NORTH WEST': 'NW',
    'NORTH EAST': 'NE',
    'NE': 'NE',
    'N': 'N',
    'EAST': 'E',
    'E': 'E',
}

HIGHWAYS_TO_STYLE = {
    'co hwy': 'County Highway ',
    'co rd': 'County Road ',
    'hwy': 'Highway ',
    'i-': 'I-',
    'rte': 'Route ',
    'state hwy': 'State Highway ',
    'state rd': 'State Road ',
    'state rte': 'State Route ',
    'us hwy': 'U.S. Highway ',
    'u.s. hwy': 'U.S. Highway ',
    'us rte': 'U.S. Route ',
    'u.s. rte': 'U.S. Route ',
}

HIGHWAYS_STATE_APPEND = [
    'state hwy',
    'state rte',
]

HIGHWAYS_TO_GEOCODER = {
    'co highway ': 'Co Hwy',
    'co hwy ': 'Co Hwy',
    'co rd ': 'Co Rd',
    'co road ': 'Co Rd',
    'highway ': 'Hwy',
    'hwy ': 'Hwy',
    'i-': 'I-',
    'i- ': 'I-',
    'route ': 'Rte',
    'rte ': 'Rte',
    'state highway ': 'State Hwy',
    'state hwy ': 'State Hwy',
    'state rd ': 'State Road',
    'state road ': 'State Road',
    'state rte ': 'State Rte',
    'state route': 'State Rte',
    'sr ': 'State Rte',
    'us ': 'US Hwy',
    'us-': 'US Hwy',
    'us highway': 'US Hwy',
    'us hwy ': 'US Hwy',
    'us route ': 'US Rte',
    'us rte ': 'US Rte',
    'wi ': 'State Hwy',
    'wi-': 'State Hwy',
    'wis ': 'State Hwy',
    'wis-': 'State Hwy',
    'wi hwy ': 'State Hwy',
    'wis hwy ': 'State Hwy',
    'wisc hwy ': 'State Hwy',
    'wisconsin hwy ': 'State Hwy',
    'wi highway': 'State Hwy',
    'wis highway': 'State Hwy',
    'wisc highway': 'State Hwy',
    'wisconsin highway': 'State Hwy',
    'wi rte ': 'State Rte',
    'wis rte ': 'State Rte',
    'wisc rte ': 'State Rte',
    'wisconsin rte ': 'State Rte',
    'wi route': 'State Rte',
    'wis route': 'State Rte',
    'wisc route': 'State Rte',
    'wisconsin route': 'State Rte',
}

KNOWN_STATE_ABBREVS = {
    'wis': 'WI',
    'wisc': 'WI',
}

STREET_NUMBERS_TO_ORDINALS = {
    '1': '1st',
    '2': '2nd',
    '3': '3rd',
    '4': '4th',
    '5': '5th',
    '6': '6th',
    '7': '7th',
    '8': '8th',
    '9': '9th',
    '10': '10th',
    '11': '11th',
    '12': '12th',
    '13': '13th',
    '14': '14th',
    '15': '15th',
    '16': '16th',
    '17': '17th',
    '18': '18th',
    '19': '19th',
    '20': '20th',
    '21': '21st',
    '22': '22nd',
    '23': '23rd',
    '24': '24th',
    '25': '25th',
    '26': '26th',
    '27': '27th',
    '28': '28th',
    '29': '29th',
    '30': '30th',
    '31': '31st',
    '32': '32nd',
    '33': '33rd',
    '34': '34th',
    '35': '35th',
    '36': '36th',
    '37': '37th',
    '38': '38th',
    '39': '39th',
    '40': '40th',
    '41': '41st',
    '42': '42nd',
    '43': '43rd',
    '44': '44th',
    '45': '45th',
    '46': '46th',
    '47': '47th',
    '48': '48th',
    '49': '49th',
    '50': '50th',
    '51': '51st',
    '52': '52nd',
    '53': '53rd',
    '54': '54th',
    '55': '55th',
    '56': '56th',
    '57': '57th',
    '58': '58th',
    '59': '59th',
    '60': '60th',
    '61': '61st',
    '62': '62nd',
    '63': '63rd',
    '64': '64th',
    '65': '65th',
    '66': '66th',
    '67': '67th',
    '68': '68th',
    '69': '69th',
    '70': '70th',
    '71': '71st',
    '72': '72nd',
    '73': '73rd',
    '74': '74th',
    '75': '75th',
    '76': '76th',
    '77': '77th',
    '78': '78th',
    '79': '79th',
    '80': '80th',
    '81': '81st',
    '82': '82nd',
    '83': '83rd',
    '84': '84th',
    '85': '85th',
    '86': '86th',
    '87': '87th',
    '88': '88th',
    '89': '89th',
    '90': '90th',
    '91': '91st',
    '92': '92nd',
    '93': '93rd',
    '94': '94th',
    '95': '95th',
    '96': '96th',
    '97': '97th',
    '98': '98th',
    '99': '99th',
    '100': '100th',
    '101': '101st',
    '102': '102nd',
    '103': '103rd',
    '104': '104th',
    '105': '105th',
    '106': '106th',
    '107': '107th',
    '108': '108th',
    '109': '109th',
    '110': '110th',
    '111': '111st',
    '112': '112nd',
    '113': '113rd',
    '114': '114th',
    '115': '115th',
    '116': '116th',
    '117': '117th',
    '118': '118th',
    '119': '119th',
    '120': '120th',
    '121': '121st',
    '122': '122nd',
    '123': '123rd',
    '124': '124th',
    '125': '125th',
    '126': '126th',
    '127': '127th',
    '128': '128th',
    '129': '129th',
    '130': '130th',
    '131': '131st',
    '132': '132nd',
    '133': '133rd',
    '134': '134th',
    '135': '135th',
    '136': '136th',
    '137': '137th',
    '138': '138th',
    '139': '139th',
    '140': '140th',
    '141': '141st',
    '142': '142nd',
    '143': '143rd',
    '144': '144th',
    '145': '145th',
    '146': '146th',
    '147': '147th',
    '148': '148th',
    '149': '149th',
    '150': '150th',
    '151': '151st',
    '152': '152nd',
    '153': '153rd',
    '154': '154th',
    '155': '155th',
    '156': '156th',
    '157': '157th',
    '158': '158th',
    '159': '159th',
}

TEXTUAL_TO_NUMERIC_ORDINALS = {
    'first': '1st',
    'second': '2nd',
    'third': '3rd',
    'fourth': '4th',
    'fifth': '5th',
    'sixth': '6th',
    'seventh': '7th',
    'eighth': '8th',
    'eigth': '8th',
    'ninth': '9th',
    'tenth': '10th',
    'eleventh': '11th',
    'twelfth': '12th',
    'thirteenth': '13th',
    'fourteenth': '14th',
    'fifteenth': '15th',
    'sixteenth': '16th',
    'seventeenth': '17th',
    'eighteenth': '18th',
    'ninteenth': '19th',
    'twentieth': '20th',
    'twenty-first': '21st',
    'twenty first': '21st',
    'twentyfirst': '21st',
    'twenty-second': '22nd',
    'twenty second': '22nd',
    'twentysecond': '22nd',
    'twenty-third': '23rd',
    'twenty third': '23rd',
    'twentythird': '23rd',
    'twenty-fourth': '24th',
    'twenty fourth': '24th',
    'twentyfourth': '24th',
    'twenty-fifth': '25th',
    'twenty fifth': '25th',
    'twentyfifth': '25th',
    'twenty-sixth': '26th',
    'twenty sixth': '26th',
    'twentysixth': '26th',
    'twenty-seventh': '27th',
    'twenty seventh': '27th',
    'twentyseventh': '27th',
    'twenty-eighth': '28th',
    'twenty eighth': '28th',
    'twentyeighth': '28th',
    'twenty-eigth': '28th',
    'twenty eigth': '28th',
    'twentyeigth': '28th',
    'twenty-ninth': '29th',
    'twenty ninth': '29th',
    'twentyninth': '29th',
    'thirtieth': '30th',
    'thirty-first': '31st',
    'thirty first': '31st',
    'thirtyfirst': '31st',
    'thirty-second': '32nd',
    'thirty second': '32nd',
    'thirtysecond': '32nd',
    'thirty-third': '33rd',
    'thirty third': '33rd',
    'thirtythird': '33rd',
    'thirty-fourth': '34th',
    'thirty fourth': '34th',
    'thirtyfourth': '34th',
    'thirty-fifth': '35th',
    'thirty fifth': '35th',
    'thirtyfifth': '35th',
    'thirty-sixth': '36th',
    'thirty sixth': '36th',
    'thirtysixth': '36th',
    'thirty-seventh': '37th',
    'thirty seventh': '37th',
    'thirtyseventh': '37th',
    'thirty-eighth': '38th',
    'thirty eighth': '38th',
    'thirtyeighth': '38th',
    'thirty-eigth': '38th',
    'thirty eigth': '38th',
    'thirtyeigth': '38th',
    'thirty-ninth': '39th',
    'thirty ninth': '39th',
    'thirtyninth': '39th',
    'fortieth': '40th',
    'fourtieth': '40th',
    'forty-first': '41st',
    'forty first': '41st',
    'fortyfirst': '41st',
    'fourty-first': '41st',
    'fourty first': '41st',
    'fourtyfirst': '41st',
    'forty-second': '42nd',
    'forty second': '42nd',
    'fortysecond': '42nd',
    'fourty-second': '42nd',
    'fourty second': '42nd',
    'fourtysecond': '42nd',
    'forty-third': '43rd',
    'forty third': '43rd',
    'fortythird': '43rd',
    'fourty-third': '43rd',
    'fourty third': '43rd',
    'fourtythird': '43rd',
    'forty-fourth': '44th',
    'forty fourth': '44th',
    'fortyfourth': '44th',
    'fourty-fourth': '44th',
    'fourty fourth': '44th',
    'fourtyfourth': '44th',
    'forty-fifth': '45th',
    'forty fifth': '45th',
    'fortyfifth': '45th',
    'fourty-fifth': '45th',
    'fourty fifth': '45th',
    'fourtyfifth': '45th',
    'forty-sixth': '46th',
    'forty sixth': '46th',
    'fortysixth': '46th',
    'fourty-sixth': '46th',
    'fourty sixth': '46th',
    'fourtysixth': '46th',
    'forty-seventh': '47th',
    'forty seventh': '47th',
    'fortyseventh': '47th',
    'fourty-seventh': '47th',
    'fourty seventh': '47th',
    'fourtyseventh': '47th',
    'forty-eighth': '48th',
    'forty eighth': '48th',
    'fortyeighth': '48th',
    'fourty-eighth': '48th',
    'fourty eighth': '48th',
    'fourtyeighth': '48th',
    'forty-eigth': '48th',
    'forty eigth': '48th',
    'fortyeigth': '48th',
    'fourty-eigth': '48th',
    'fourty eigth': '48th',
    'fourtyeigth': '48th',
    'forty-ninth': '49th',
    'forty ninth': '49th',
    'fortyninth': '49th',
    'fourty-ninth': '49th',
    'fourty ninth': '49th',
    'fourtyninth': '49th',
    'fiftieth': '50th',
    'fifty-first': '51st',
    'fifty first': '51st',
    'fiftyfirst': '51st',
    'fifty-second': '52nd',
    'fifty second': '52nd',
    'fiftysecond': '52nd',
    'fifty-third': '53rd',
    'fifty third': '53rd',
    'fiftythird': '53rd',
    'fifty-fourth': '54th',
    'fifty fourth': '54th',
    'fiftyfourth': '54th',
    'fifty-fifth': '55th',
    'fifty fifth': '55th',
    'fiftyfifth': '55th',
    'fifty-sixth': '56th',
    'fifty sixth': '56th',
    'fiftysixth': '56th',
    'fifty-seventh': '57th',
    'fifty seventh': '57th',
    'fiftyseventh': '57th',
    'fifty-eighth': '58th',
    'fifty eighth': '58th',
    'fiftyeighth': '58th',
    'fifty-eigth': '58th',
    'fifty eigth': '58th',
    'fiftyeigth': '58th',
    'fifty-ninth': '59th',
    'fifty ninth': '59th',
    'fiftyninth': '59th',
    'sixtieth': '60th',
    'sixty-first': '61st',
    'sixty first': '61st',
    'sixtyfirst': '61st',
    'sixty-second': '62nd',
    'sixty second': '62nd',
    'sixtysecond': '62nd',
    'sixty-third': '63rd',
    'sixty third': '63rd',
    'sixtythird': '63rd',
    'sixty-fourth': '64th',
    'sixty fourth': '64th',
    'sixtyfourth': '64th',
    'sixty-fifth': '65th',
    'sixty fifth': '65th',
    'sixtyfifth': '65th',
    'sixty-sixth': '66th',
    'sixty sixth': '66th',
    'sixtysixth': '66th',
    'sixty-seventh': '67th',
    'sixty seventh': '67th',
    'sixtyseventh': '67th',
    'sixty-eighth': '68th',
    'sixty eighth': '68th',
    'sixtyeighth': '68th',
    'sixty-eigth': '68th',
    'sixty eigth': '68th',
    'sixtyeigth': '68th',
    'sixty-ninth': '69th',
    'sixty ninth': '69th',
    'sixtyninth': '69th',
    'seventieth': '70th',
    'seventy-first': '71st',
    'seventy first': '71st',
    'seventyfirst': '71st',
    'seventy-second': '72nd',
    'seventy second': '72nd',
    'seventysecond': '72nd',
    'seventy-third': '73rd',
    'seventy third': '73rd',
    'seventythird': '73rd',
    'seventy-fourth': '74th',
    'seventy fourth': '74th',
    'seventyfourth': '74th',
    'seventy-fifth': '75th',
    'seventy fifth': '75th',
    'seventyfifth': '75th',
    'seventy-sixth': '76th',
    'seventy sixth': '76th',
    'seventysixth': '76th',
    'seventy-seventh': '77th',
    'seventy seventh': '77th',
    'seventyseventh': '77th',
    'seventy-eighth': '78th',
    'seventy eighth': '78th',
    'seventyeighth': '78th',
    'seventy-eigth': '78th',
    'seventy eigth': '78th',
    'seventyeigth': '78th',
    'seventy-ninth': '79th',
    'seventy ninth': '79th',
    'seventyninth': '79th',
    'eightieth': '80th',
    'eigtieth': '80th',
    'eighty-first': '81st',
    'eighty first': '81st',
    'eightyfirst': '81st',
    'eigty-first': '81st',
    'eigty first': '81st',
    'eigtyfirst': '81st',
    'eighty-second': '82nd',
    'eighty second': '82nd',
    'eightysecond': '82nd',
    'eigty-second': '82nd',
    'eigty second': '82nd',
    'eigtysecond': '82nd',
    'eighty-third': '83rd',
    'eighty third': '83rd',
    'eightythird': '83rd',
    'eigty-third': '83rd',
    'eigty third': '83rd',
    'eigtythird': '83rd',
    'eighty-fourth': '84th',
    'eighty fourth': '84th',
    'eightyfourth': '84th',
    'eigty-fourth': '84th',
    'eigty fourth': '84th',
    'eigtyfourth': '84th',
    'eighty-fifth': '85th',
    'eighty fifth': '85th',
    'eightyfifth': '85th',
    'eigty-fifth': '85th',
    'eigty fifth': '85th',
    'eigtyfifth': '85th',
    'eighty-sixth': '86th',
    'eighty sixth': '86th',
    'eightysixth': '86th',
    'eigty-sixth': '86th',
    'eigty sixth': '86th',
    'eigtysixth': '86th',
    'eighty-seventh': '87th',
    'eighty seventh': '87th',
    'eightyseventh': '87th',
    'eigty-seventh': '87th',
    'eigty seventh': '87th',
    'eigtyseventh': '87th',
    'eighty-eighth': '88th',
    'eighty eighth': '88th',
    'eightyeighth': '88th',
    'eigty-eighth': '88th',
    'eigty eighth': '88th',
    'eigtyeighth': '88th',
    'eighty-eigth': '88th',
    'eighty eigth': '88th',
    'eightyeigth': '88th',
    'eigty-eigth': '88th',
    'eigty eigth': '88th',
    'eigtyeigth': '88th',
    'eighty-ninth': '89th',
    'eighty ninth': '89th',
    'eightyninth': '89th',
    'eigty-ninth': '89th',
    'eigty ninth': '89th',
    'eigtyninth': '89th',
    'ninetieth': '90th',
    'nintieth': '90th',
    'ninety-first': '91st',
    'ninety first': '91st',
    'ninetyfirst': '91st',
    'ninty-first': '91st',
    'ninty first': '91st',
    'nintyfirst': '91st',
    'ninety-second': '92nd',
    'ninety second': '92nd',
    'ninetysecond': '92nd',
    'ninty-second': '92nd',
    'ninty second': '92nd',
    'nintysecond': '92nd',
    'ninety-third': '93rd',
    'ninety third': '93rd',
    'ninetythird': '93rd',
    'ninty-third': '93rd',
    'ninty third': '93rd',
    'nintythird': '93rd',
    'ninety-fourth': '94th',
    'ninety fourth': '94th',
    'ninetyfourth': '94th',
    'ninty-fourth': '94th',
    'ninty fourth': '94th',
    'nintyfourth': '94th',
    'ninety-fifth': '95th',
    'ninety fifth': '95th',
    'ninetyfifth': '95th',
    'ninty-fifth': '95th',
    'ninty fifth': '95th',
    'nintyfifth': '95th',
    'ninety-sixth': '96th',
    'ninety sixth': '96th',
    'ninetysixth': '96th',
    'ninty-sixth': '96th',
    'ninty sixth': '96th',
    'nintysixth': '96th',
    'ninety-seventh': '97th',
    'ninety seventh': '97th',
    'ninetyseventh': '97th',
    'ninty-seventh': '97th',
    'ninty seventh': '97th',
    'nintyseventh': '97th',
    'ninety-eighth': '98th',
    'ninety eighth': '98th',
    'ninetyeighth': '98th',
    'ninty-eighth': '98th',
    'ninty eighth': '98th',
    'nintyeighth': '98th',
    'ninety-eigth': '98th',
    'ninety eigth': '98th',
    'ninetyeigth': '98th',
    'ninty-eigth': '98th',
    'ninty eigth': '98th',
    'nintyeigth': '98th',
    'ninety-ninth': '99th',
    'ninety ninth': '99th',
    'ninetyninth': '99th',
    'ninty-ninth': '99th',
    'ninty ninth': '99th',
    'nintyninth': '99th',
}
